[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

[[bin]]
edition = "2021"
name = "raytracing"
path = "src/main.rs"

[dependencies]
image = "0.25.5"
rand = "^0.8.5"
rayon = "1.10.0"
threadpool = "1.8.1"
